all:
	g++ -std=c++17 -lstdc++fs Principal.cpp -I/home/jeison/opencv_build/opencv/opencvi/include/opencv4/ -L/home/jeison/opencv_build/opencv/build/lib/ -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio -lopencv_ml -lopencv_objdetect -lopencv_features2d -o vision.bin



run:
	./vision.bin